Adiciona paginas
matheustirabassi/gg-learning pull request #57
Opened 2022-08-04 18:44 UTC by miguelsbrissa

Adiciona páginas:
- Homepage
- Todos os artigos
- Artigo
- Quizz 

Cria componente de layout base de página

2022-08-05 18:36 UTC, matheustirabassi requested changes

2022-08-05 18:36 UTC, matheustirabassi commented on frontend/src/presentation/components/LayoutBaseDePagina/LayoutBaseDePagina.tsx
> +                    mostrarMenu && (
Trocar para português também

2022-08-05 18:36 UTC, matheustirabassi commented on frontend/src/presentation/components/LayoutBaseDePagina/LayoutBaseDePagina.tsx
> +                    mostrarSideRodape && (
Aqui também

2022-08-05 18:36 UTC, matheustirabassi commented on frontend/src/presentation/components/LayoutBaseDePagina/LayoutBaseDePagina.tsx
> +                    mostrarRodape && (
Aqui

2022-08-05 18:36 UTC, matheustirabassi commented on frontend/src/presentation/view/HomePage/HomeContentView.tsx
>  // function useViewModel() {
Remover comentário

2022-08-05 18:36 UTC, matheustirabassi commented on frontend/src/presentation/view/HomePage/HomeContentView.tsx
>  	// const { textButton, onChange } = useViewModel()
Aqui também

2022-08-05 18:42 UTC, matheustirabassi reviewed
na próxima cria a branch cm o sufixo `feature/`. Isso nos ajuda porque assim sabemos como incrementando a versão no deploy

2022-08-05 19:09 UTC, miguelsbrissa commented on frontend/src/index.css
> +}
sim mas antes era .scss dai como nao tamo usando nada de sass troquei por um css msm

2022-08-05 19:13 UTC, miguelsbrissa commented on frontend/src/presentation/components/Header/Header.tsx
> +function Header() {
blz, mas o link não abriu aqui não

2022-08-05 19:29 UTC, miguelsbrissa commented on frontend/src/presentation/components/Question/Question.tsx
> +}
os links não tão abrindo acho q o repo dever estar privado

2022-08-06 14:34 UTC, matheustirabassi commented on frontend/src/index.css
> +}
boa!

2022-08-06 14:34 UTC, matheustirabassi commented on frontend/src/presentation/components/Header/Header.tsx
> +function Header() {
https://raw.githubusercontent.com/matheustirabassi/cezar-encript/main/src/i18n.ts?token=GHSAT0AAAAAABXKRJ6YU2F7TB45AMX4TJGGYXOPQ7A

2022-08-06 14:37 UTC, matheustirabassi requested changes
sobre o netlify, teve alguns erros de variáveis não usadas
https://app.netlify.com/sites/gglearning/deploys/62ec72de0e71a900098a7e9f

2022-08-06 15:03 UTC, miguelsbrissa commented on frontend/src/presentation/components/Header/Header.tsx
> +function Header() {
![image](https://user-images.githubusercontent.com/84507810/183254687-6a1e268f-7f5b-4e2f-8ef4-c1fdfa6a38fa.png)

não abriu dnv

2022-08-06 15:18 UTC, matheustirabassi commented on frontend/src/presentation/components/Header/Header.tsx
> +function Header() {
tenta de novo, mudei a visibilidade do repositório para publico

2022-08-06 15:27 UTC, miguelsbrissa commented on frontend/src/presentation/components/Header/Header.tsx
> +function Header() {
agora foi

2022-08-06 17:02 UTC, matheustirabassi commented
@miguelsbrissa você pode fazer as mudanças e commitar, assim posso revisar de novo

2022-08-08 18:01 UTC, matheustirabassi approved these changes
Boa! Agora incrementa a versão no frontend

2022-08-09 00:52 UTC, matheustirabassi requested changes

2022-08-09 00:52 UTC, matheustirabassi commented on frontend/src/Routes.tsx
> +	COMPILADOR:"/compilador"
já que vamos deixar as urls em inglês, acho que seria interessante deixar o compilador em inglês também

2022-08-09 00:52 UTC, matheustirabassi commented on frontend/src/presentation/components/Header/Header.tsx
> +	//const open = Boolean(anchorEl)
isso não ta usando mais né?

2022-08-10 19:57 UTC, matheustirabassi approved these changes

2022-08-10 19:57 UTC, merged