feat: :sparkles: Adiciona ViewModel para tela de criar conta
matheustirabassi/gg-learning pull request #81
Opened 2022-09-08 15:38 UTC by miguelsbrissa

78

2022-09-09 01:43 UTC, matheustirabassi requested changes

2022-09-09 01:43 UTC, matheustirabassi commented on frontend/src/presentation/view/CreateAccountPage/CreateAccountContentViewModel.ts
> +}
Acho que seria melhor criar um DTO pra o usuário

2022-09-09 01:43 UTC, matheustirabassi commented on frontend/src/presentation/view/CreateAccountPage/CreateAccountContentViewModel.ts
> +        }
Talvez seria melhor um UserAPI, pra guardar as requisições do usuário, e só fazer a chamada pelo ViewModel

2022-09-09 22:27 UTC, miguelsbrissa commented on frontend/src/presentation/view/CreateAccountPage/CreateAccountContentViewModel.ts
> +        }
boa dai da pra por nesse UserAPI a parte de visualizar o usuario também dps

2022-09-09 23:06 UTC, miguelsbrissa commented on frontend/src/presentation/view/CreateAccountPage/CreateAccountContentViewModel.ts
> +}
não sei se precisa disso pq é meio simples o nosso projeto

2022-09-10 13:28 UTC, miguelsbrissa commented
@matheustirabassi eu criei o UserAPI e coloquei a interface lá também acho q não precisa criar um DTO pq o nosso projeto é mais simples

2022-09-13 00:45 UTC, matheustirabassi approved these changes

2022-09-13 00:48 UTC, matheustirabassi approved these changes

2022-09-13 15:53 UTC, merged