Tela de cadastro de artigo
matheustirabassi/gg-learning pull request #83
Opened 2022-09-13 15:54 UTC by miguelsbrissa

2022-09-21 23:59 UTC, matheustirabassi requested changes

2022-09-21 23:59 UTC, matheustirabassi commented on frontend/src/presentation/components/CreateArticle/CreateArticle.tsx
> +    // }
remover

2022-09-21 23:59 UTC, matheustirabassi commented on frontend/src/presentation/components/CreateArticle/CreateArticle.tsx
> +    //handleSubmit
deletar comentário

2022-09-26 14:51 UTC, matheustirabassi approved these changes

2022-09-27 23:27 UTC, miguelsbrissa commented
@matheustirabassi ainda ta dando erro de cors e não aparece o header completo

2022-10-04 12:39 UTC, matheustirabassi requested changes

2022-10-04 12:39 UTC, matheustirabassi commented on frontend/src/data/dto/QuestionDTO.ts
> +        this.correctAlternative = correctAlternative
mudar para answer

2022-10-05 02:50 UTC, merged